# Usage:
# docker-compose build && docker-compose up
version: '2'

services:
  grocy-nginx:
    build:
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    ports:
      - '80:80'
      - '443:443'
    volumes_from:
      - grocy
    container_name: grocy-nginx

  grocy:
    build:
      context: .
      dockerfile: Dockerfile-grocy
    expose:
      - 9000
    environment:
      PHP_MEMORY_LIMIT:    512M
      MAX_UPLOAD:          50M
      PHP_MAX_FILE_UPLOAD: 200
      PHP_MAX_POST:        100M
    container_name: grocy