
site_name: Grocy Documentation
site_url: https://grocy.readthedocs.io/
repo_url: https://github.com/grocy/grocy
theme:
    name: readthedocs
    navigation_depth: 3
markdown_extensions:
    - admonition:

nav:
    - Introduction: 'index.md'