apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: {{ include "chart.fullname" . }}
  name: grocy-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
